config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about'
  devise_for :users
  resources :users, :only => [:show, :index, :edit, :update] do
  	resource :relationships, only: [:create, :destroy]
  		get :follows, on: :member
  		get :followers, on: :member
  end
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end
  get "search" => "searchs#search"
end

app/models/book_comment.rb
class BookComment < ApplicationRecord


	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

	def create
		book = Book.find(params[:book_id])
		comment = current_user.book_comments.new(book_comment_params)
		comment.book_id = book.id
		comment.save
		redirect_to book_path(book.id)
	end

	def destroy
		book = Book.find(params[:book_id])
		comment = current_user.book_comments.find(params[:id])
	 if	comment.destroy
		redirect_back(fallback_location: root_path)
	 else
		render :show
	 end
    end

	private
	def book_comment_params
		params.require(:book_comment).permit(:user_id, :book_id, :comment)
	end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment.html.erb
<table class="table">

	<% book.book_comments.each do |bookcomment| %>

	<tr>

		<td><%= bookcomment.user.name %></td>

		<td><%= bookcomment.comment %></td>

		<% if (current_user == bookcomment.user) %>

		<td><%= link_to "Destroy",book_book_comment_path(@book.id,bookcomment.id), method: :delete, "data-confirm" => "本当に削除してもよろしいですか？", class: "btn-sm btn-danger" %></td>

		<% else %>

		<td></td>

		<% end %>

	</tr>

	<% end %>

</table>




<%= form_for [book, book_comment] do |f| %>
	<div class="row">
		<div class="col-sm-12">
		<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
		</div>
	</div>
		<%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
		<% end %>