config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about'
  devise_for :users
  resources :users, :only => [:show, :index, :edit, :update] do
  	resource :relationships, only: [:create, :destroy]
  		get :follows, on: :member
  		get :followers, on: :member
  end
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end
  get "search" => "searchs#search"
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
	def search
		@user_or_book = params[:option]
		@how_search = params[:choice]
		if @user_or_book == "1"
			@users = User.search(params[:search], @how_search, @user_or_book)
		else
			@books = Book.search(params[:search], @how_search, @user_or_book)
		end
	end

end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searchs/search.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">

            
                <br>

                <h4>Users search for 'test</h4>

                <table class="table table-hover table-inverse">
                    
                    <tbody>

                        <tr>
                                <% if @user_or_book == "1"%>

                                    <thead>


                                        <tr>
                                            <th>image</th>
                                            <th>name</th>
                                            <th></th>
                                        </tr>

                                    </thead>

                                    <% @users.each do |user| %>

                                    <tr>
                                            <th><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></th>
                                            <th><%= user.name %></th>
                                            <th><%=link_to "show", user_path(user.id) %></th>
                                    </tr>
                                    <% end %>
                             
                            <% elsif @user_or_book == "2" %>

                                    <thead>


                                        <tr>
                                            <th>image</th>
                                            <th>title</th>
                                            <th></th>
                                        </tr>

                                    </thead>
                                <% @books.each do |book| %>

                                        <tr>
                                            <th><%= attachment_image_tag(book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></th>
                                            <th><%= book.title %></th>
                                            <th><%=link_to "show", book_path(book.id) %></th>

                                        </tr>
                                <% end %>
                            <% else %>
                            <% end %>
                        </tr>
                    </tbody>
                </table>